### PR TITLE
Schema versions cache fix

### LINKED ISSUE #607: Topic schema versions cache gets cleared on schema registry unavailability
It looks like we override the cached value of schema versions when we get an error response from underlying schema repository. The version cache is overwritten with an empty list.

### PR DESCRIPTION
**Pull request by dankraw**
This fix changes the behaviour of schema repository clients, as they previously didn't throw proper exceptions when schema repository underneath returned server errors etc.
Cache itself works properly.

fixes #607

### CODE REVIEW

File: hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/schemarepo/SchemaRepoRawSchemaClient.java [hunk 1]
```diff
@@ -39,30 +41,66 @@ public SchemaRepoRawSchemaClient(Client client, URI schemaRepoServerUri) {
...
+                .request()
+                .accept(MediaType.APPLICATION_JSON_TYPE)
+                .get();
+        return extractSchemaVersions(topic.qualifiedName(), response);
+    }
+
+    private List<SchemaVersion> extractSchemaVersions(String subject, Response response) {
+        switch (response.getStatusInfo().getFamily()) {
+            case SUCCESSFUL:
+                List<SchemaWithId> schemasWithIds = Optional.ofNullable(response.readEntity(new GenericType<List<SchemaWithId>>() {}))
```
Comment (sputnikci) [inline hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/schemarepo/SchemaRepoRawSchemaClient.java]: \[Checkstyle\] ERROR: '\}' is not preceded with whitespace\.
