### PR TITLE
Schema-related frontend responses fix

### LINKED ISSUE #620: Schema-related frontend responses
Hermes responses with 408 when schema for Avro topic is not defined. It should respond with 500 as before (0.8 branch).

### PR DESCRIPTION
**Pull request by dankraw**
Fixes #620

### CODE REVIEW

File: hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaRepository.java [hunk 1]
```diff
@@ -39,7 +39,17 @@ public SchemaRepository(SchemaVersionsRepository schemaVersionsRepository,
...
      */
     public CompiledSchema<Schema> getKnownAvroSchemaVersion(Topic topic, SchemaVersion version) {
-        return compiledAvroSchemaRepository.getSchema(topic, version);
+        return getCompiledSchemaAtVersion(topic, version);
+    }
+
+    private CompiledSchema<Schema> getCompiledSchemaAtVersion(Topic topic, SchemaVersion latestVersion) {
+        try {
+            return compiledAvroSchemaRepository.getSchema(topic, latestVersion);
+        } catch (CouldNotLoadSchemaException e) {
```
Comment (sputnikci) [inline hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaRepository.java]: \[PMD\] INFO: A catch statement that catches an exception only to rethrow it should be avoided\.

File: hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaRepository.java [hunk 2]
```diff
@@ -39,7 +39,18 @@ public SchemaRepository(SchemaVersionsRepository schemaVersionsRepository,
...
     public CompiledSchema<Schema> getKnownAvroSchemaVersion(Topic topic, SchemaVersion version) {
-        return compiledAvroSchemaRepository.getSchema(topic, version);
+        return getCompiledSchemaAtVersion(topic, version);
+    }
+
+    private CompiledSchema<Schema> getCompiledSchemaAtVersion(Topic topic, SchemaVersion latestVersion) {
+        try {
+            return compiledAvroSchemaRepository.getSchema(topic, latestVersion);
+        } catch (Exception e) {
+            if (e instanceof CouldNotLoadSchemaException) {
```
Comment (sputnikci) [inline hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaRepository.java]: \[PMD\] INFO: An instanceof check is being performed on the caught exception\.  Create a separate catch clause for this exception type\.

File: hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaRepository.java (hunk 1 above)
Comment (sputnikci) [inline hermes-schema/src/main/java/pl/allegro/tech/hermes/schema/SchemaRepository.java]: \[PMD\] IGNORE: A catch statement that catches an exception only to rethrow it should be avoided\.
