### PR TITLE
fix BasicAuth credentials update

### LINKED ISSUE #499: Updating credentials of basic authentication clears them from subscription
If subscription endpoint uses basic authentication, update of subscription with same endpoint but with new credentials results in subscription with endpoint with no credentials.

### PR DESCRIPTION
**Pull request by adamdubiel**
Resolves #499

### CODE REVIEW

**Comment by druminski** [comment]
👍

File: hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java [hunk 1]
```diff
@@ -2,7 +2,16 @@
 
 import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Component;
-import pl.allegro.tech.hermes.api.*;
+import pl.allegro.tech.hermes.api.MessageTrace;
```
Comment (druminski) [inline hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java]: this file don't need to be touched, imo it would be nice to use the same code style schema in our IDE

Comment (adamdubiel) [inline hermes-management/src/main/java/pl/allegro/tech/hermes/management/domain/subscription/SubscriptionService.java]: yes, you are right - we should prepare "official" IntelliJ format

File: integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java [hunk 2]
```diff
@@ -1,13 +1,17 @@
 package pl.allegro.tech.hermes.integration;
 
+import com.google.common.collect.Maps;
```
Comment (sputnikci) [inline integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java]: \[Checkstyle\] ERROR: Unused import \- com\.google\.common\.collect\.Maps\.

File: integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java [hunk 3]
```diff
@@ -1,13 +1,17 @@
...
 import org.testng.annotations.BeforeMethod;
 import org.testng.annotations.Test;
+import pl.allegro.tech.hermes.api.PatchData;
```
Comment (sputnikci) [inline integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java]: \[Checkstyle\] ERROR: Unused import \- pl\.allegro\.tech\.hermes\.api\.PatchData\.

File: integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java [hunk 4]
```diff
@@ -22,7 +26,7 @@ public void initializeAlways() {
     public void shouldAuthorizeUsingBasicAuthWhenSubscriptionHasCredentials() {
         // given
         Topic topic = operations.buildTopic("basicAuthGroup", "topic");
-        operations.createSubscription(topic, "subscription", "http://user:password@localhost:" + HTTP_ENDPOINT_PORT + "/" );
+        operations.createSubscription(topic, "subscription", "http://user:password@localhost:" + HTTP_ENDPOINT_PORT + "/");
```
Comment (sputnikci) [inline integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java]: \[PMD\] INFO: The String literal "subscription" appears 4 times in this file; the first occurrence is on line 29

Comment (adamdubiel) [inline integration/src/integration/java/pl/allegro/tech/hermes/integration/BasicAuthSubscribingTest.java]: ignore - test code is fine with repetitions

File: hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java [hunk 5]
```diff
@@ -31,45 +26,58 @@
 public class JerseySchemaRepoClientTest {
 
     private static final String ROOT_DIR = "/schema-repo/";
-    private static final String SUBJECT = "some.subject";
+    private static final int PORT = Ports.nextAvailable();
 
-    private static final SchemaRepoClient client = new JerseySchemaRepoClient(ClientBuilder.newClient(), URI.create("http://localhost:2876/schema-repo/"));
+    private static final SchemaRepoClient client = new JerseySchemaRepoClient(
```
Comment (sputnikci) [inline hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java]: \[Checkstyle\] ERROR: Name 'client' must match pattern '^\[A\-Z\]\[A\-Z0\-9\]\*\(\_\[A\-Z0\-9\]\+\)\*|logger\*$'\.

File: hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java [hunk 6]
```diff
@@ -31,45 +26,58 @@
...
+            ClientBuilder.newClient(),
+            URI.create("http://localhost:" + PORT + ROOT_DIR)
+    );
 
-    @Rule
-    public final WireMockRule wireMockRule = new WireMockRule(wireMockConfig().port(2876).usingFilesUnderClasspath("schema-repo-stub"));
+    @ClassRule
+    public static final WireMockRule wireMock = new WireMockRule(
```
Comment (sputnikci) [inline hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java]: \[Checkstyle\] ERROR: Name 'wireMock' must match pattern '^\[A\-Z\]\[A\-Z0\-9\]\*\(\_\[A\-Z0\-9\]\+\)\*|logger\*$'\.

File: hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java (hunk 5 above)
Comment (adamdubiel) [inline hermes-common/src/test/java/pl/allegro/tech/hermes/infrastructure/schema/repo/JerseySchemaRepoClientTest.java]: ignoring both - reads better in test code
